### PR TITLE
update to netstadard1.3

### PR DESCRIPTION
**Pull request by Jetski5822**
- Upgrade to netstandard1.3 (Serialise Attribute stopped the move to 1.1)
 - Removed all portable libs as no longer required

### CODE REVIEW

**Comment by wis3guy** [comment]
@Jetski5822 Thanks foor doing this!

It seems you turned this into netcore projects, correct?

Note that the build fails since your last commit.

**Comment by Jetski5822** [comment]
Hey @wis3guy - yup all .netstandard :)

It says it builds on Appveyor, where do you see the error?

Currently upgrading the WebHal project too. That ones a bit trickier

**Comment by wis3guy** [comment]
@Jetski5822 yes i see you are right. The build succeeds, it only failed after your first commit (i had the order confused).

I will review this in the near future.

**Comment by Jetski5822** [comment]
Saweeet!!! Thanks man.

**Comment by Jetski5822** [comment]
Hey @wis3guy - have you got any bandwidth to check this PR out?

**Comment by wis3guy** [comment]
@Jetski5822 Thanks again for doing this!

**Pull request merged**
